{{- if and .Values.s3Credentials.enabled (not .Values.s3Credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mtrgraph.s3SecretName" . }}
  labels:
    {{- include "mtrgraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3Credentials.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3Credentials.secretKey | quote }}
  {{- if .Values.s3Credentials.sessionToken }}
  AWS_SESSION_TOKEN: {{ .Values.s3Credentials.sessionToken | quote }}
  {{- end }}
{{- end }}
