apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mtrgraph-data
  namespace: mtrgraph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard   # ← décommente et adapte si besoin
